#!/bin/bash
#
# Sync Copilot Chat Backups to GitHub
# ====================================
# Pushes backup data to an orphan branch in your repo
# Keeps chat history versioned without polluting main branch
#
# Usage:
#   ./sync-to-github.sh              # Sync to default branch (copilot-backup-data)
#   ./sync-to-github.sh --branch X   # Sync to custom branch
#   ./sync-to-github.sh --init       # Initialize the backup branch
#   ./sync-to-github.sh --status     # Check sync status

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="/mnt/NTFS-Data/GitHub-SSD/aiconnects-hub"
BACKUP_PATH="$HOME/copilot-chat-backups"
BACKUP_BRANCH="copilot-backup-data"
REMOTE="origin"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() {
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════════════╗"
    echo "║         Copilot Chat Backup - GitHub Sync                         ║"
    echo "╚═══════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Parse arguments
COMMAND="sync"
while [[ $# -gt 0 ]]; do
    case $1 in
        --branch)
            BACKUP_BRANCH="$2"
            shift 2
            ;;
        --init)
            COMMAND="init"
            shift
            ;;
        --status)
            COMMAND="status"
            shift
            ;;
        --help|-h)
            COMMAND="help"
            shift
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

init_branch() {
    echo -e "${YELLOW}🔧 Initializing backup branch: $BACKUP_BRANCH${NC}\n"
    
    cd "$REPO_ROOT"
    
    # Check if branch already exists remotely
    if git ls-remote --heads $REMOTE "$BACKUP_BRANCH" | grep -q "$BACKUP_BRANCH"; then
        echo -e "${YELLOW}Branch already exists on remote. Fetching...${NC}"
        git fetch $REMOTE "$BACKUP_BRANCH"
        echo -e "${GREEN}✓ Branch fetched${NC}"
        return 0
    fi
    
    # Save current branch
    CURRENT_BRANCH=$(git branch --show-current)
    
    # Create orphan branch (no history from main)
    echo "Creating orphan branch..."
    git checkout --orphan "$BACKUP_BRANCH"
    
    # Remove all files from staging
    git rm -rf . 2>/dev/null || true
    git clean -fd 2>/dev/null || true
    
    # Create initial structure
    mkdir -p daily hourly ai-export index
    
    # Create README for the branch
    cat > README.md << 'EOF'
# Copilot Chat Backup Data

This branch contains automated backups of GitHub Copilot chat sessions.

## Structure

```
├── daily/           # Daily activity summaries (Markdown)
├── hourly/          # Hourly incremental summaries
├── ai-export/       # AI-friendly exports (JSON/JSONL)
│   ├── qa_pairs.jsonl      # Q&A pairs for RAG/training
│   ├── sessions.jsonl      # All sessions streaming format
│   └── latest_export.json  # Full structured export
├── index/           # Project and session indexes
└── stats/           # Usage statistics
```

## Usage

These exports are designed for:
- **AI Training**: Use `qa_pairs.jsonl` for fine-tuning or RAG
- **Activity Tracking**: Review `daily/*.md` for daily summaries
- **Search**: Query `latest_export.json` for full context

## Automation

Backups are synced automatically via cron:
- Hourly incremental (work hours)
- Daily full backup (11:30 PM)
- Weekly archive (Sunday 2 AM)

---
*Auto-generated by copilot-backup system*
EOF

    # Create .gitignore for this branch
    cat > .gitignore << 'EOF'
# Keep exports clean
*.tmp
*.bak
*.db
raw/
markdown/
EOF

    # Initial commit
    git add .
    git commit -m "chore: initialize copilot backup data branch"
    
    # Push to remote
    git push -u $REMOTE "$BACKUP_BRANCH"
    
    # Return to original branch
    git checkout "$CURRENT_BRANCH"
    
    echo -e "\n${GREEN}✅ Backup branch initialized: $BACKUP_BRANCH${NC}"
    echo -e "   View at: https://github.com/howaiconnects/aiconnects-hub/tree/$BACKUP_BRANCH"
}

sync_backups() {
    echo -e "${YELLOW}📤 Syncing backups to GitHub...${NC}\n"
    
    # Verify backup directory exists
    if [ ! -d "$BACKUP_PATH" ]; then
        echo -e "${RED}Error: Backup directory not found: $BACKUP_PATH${NC}"
        exit 1
    fi
    
    cd "$REPO_ROOT"
    
    # Save current branch
    CURRENT_BRANCH=$(git branch --show-current)
    CURRENT_STASH=""
    
    # Stash any uncommitted changes
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
        echo "Stashing current changes..."
        git stash push -m "copilot-backup-sync-$(date +%s)"
        CURRENT_STASH="yes"
    fi
    
    # Fetch and checkout backup branch
    git fetch $REMOTE "$BACKUP_BRANCH" 2>/dev/null || {
        echo -e "${YELLOW}Branch not found. Run --init first.${NC}"
        [ -n "$CURRENT_STASH" ] && git stash pop
        exit 1
    }
    
    git checkout "$BACKUP_BRANCH"
    git pull $REMOTE "$BACKUP_BRANCH" --rebase 2>/dev/null || true
    
    # Sync directories (only the shareable ones, not raw data)
    echo "Copying backup data..."
    
    # Daily summaries
    if [ -d "$BACKUP_PATH/daily" ]; then
        mkdir -p daily
        cp -r "$BACKUP_PATH/daily/"*.md daily/ 2>/dev/null || true
        echo -e "  ${GREEN}✓${NC} daily/"
    fi
    
    # Hourly summaries  
    if [ -d "$BACKUP_PATH/hourly" ]; then
        mkdir -p hourly
        cp -r "$BACKUP_PATH/hourly/"*.md hourly/ 2>/dev/null || true
        echo -e "  ${GREEN}✓${NC} hourly/"
    fi
    
    # AI exports (limit size - only latest)
    if [ -d "$BACKUP_PATH/ai-export" ]; then
        mkdir -p ai-export
        # Copy JSONL files (streaming format, good for git)
        cp "$BACKUP_PATH/ai-export/qa_pairs.jsonl" ai-export/ 2>/dev/null || true
        cp "$BACKUP_PATH/ai-export/sessions.jsonl" ai-export/ 2>/dev/null || true
        # Latest export (full JSON)
        cp "$BACKUP_PATH/ai-export/latest_export.json" ai-export/ 2>/dev/null || true
        echo -e "  ${GREEN}✓${NC} ai-export/"
    fi
    
    # Index files
    if [ -d "$BACKUP_PATH/index" ]; then
        mkdir -p index
        cp -r "$BACKUP_PATH/index/"*.json index/ 2>/dev/null || true
        echo -e "  ${GREEN}✓${NC} index/"
    fi
    
    # Generate stats
    mkdir -p stats
    cat > stats/latest.json << EOF
{
    "synced_at": "$(date -Iseconds)",
    "sessions": $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(*) FROM sessions;" 2>/dev/null || echo 0),
    "projects": $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(DISTINCT project_name) FROM sessions;" 2>/dev/null || echo 0),
    "last_backup": "$(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT MAX(timestamp) FROM backups;" 2>/dev/null || echo "unknown")",
    "daily_files": $(ls -1 daily/*.md 2>/dev/null | wc -l),
    "qa_pairs": $(wc -l < ai-export/qa_pairs.jsonl 2>/dev/null || echo 0)
}
EOF
    echo -e "  ${GREEN}✓${NC} stats/"
    
    # Check if there are changes to commit
    if git diff --quiet && git diff --staged --quiet; then
        echo -e "\n${BLUE}No changes to sync${NC}"
    else
        # Add all changes
        git add -A
        
        # Commit with timestamp
        COMMIT_MSG="chore(backup): sync copilot chats $(date +%Y-%m-%d)"
        
        # Add stats to commit message
        SESSIONS=$(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(*) FROM sessions;" 2>/dev/null || echo "?")
        COMMIT_MSG="$COMMIT_MSG

Sessions: $SESSIONS
Projects: $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(DISTINCT project_name) FROM sessions;" 2>/dev/null || echo "?")"
        
        git commit -m "$COMMIT_MSG"
        
        # Push to remote
        git push $REMOTE "$BACKUP_BRANCH"
        
        echo -e "\n${GREEN}✅ Synced to GitHub!${NC}"
        echo -e "   Branch: $BACKUP_BRANCH"
        echo -e "   URL: https://github.com/howaiconnects/aiconnects-hub/tree/$BACKUP_BRANCH"
    fi
    
    # Return to original branch
    git checkout "$CURRENT_BRANCH"
    
    # Restore stashed changes
    if [ -n "$CURRENT_STASH" ]; then
        git stash pop
    fi
}

show_status() {
    echo -e "${BLUE}📊 GitHub Sync Status${NC}\n"
    
    cd "$REPO_ROOT"
    
    # Check if branch exists
    echo "Backup Branch: $BACKUP_BRANCH"
    if git ls-remote --heads $REMOTE "$BACKUP_BRANCH" 2>/dev/null | grep -q "$BACKUP_BRANCH"; then
        echo -e "  ${GREEN}✓ Exists on remote${NC}"
        
        # Get last commit info
        git fetch $REMOTE "$BACKUP_BRANCH" 2>/dev/null
        LAST_COMMIT=$(git log $REMOTE/$BACKUP_BRANCH -1 --format="%h %s (%ar)" 2>/dev/null)
        echo "  Last commit: $LAST_COMMIT"
        
        # Show branch URL
        echo "  URL: https://github.com/howaiconnects/aiconnects-hub/tree/$BACKUP_BRANCH"
    else
        echo -e "  ${RED}✗ Not found on remote${NC}"
        echo "  Run: ./sync-to-github.sh --init"
    fi
    
    echo ""
    
    # Local backup stats
    echo "Local Backup:"
    if [ -f "$BACKUP_PATH/backup_tracking.db" ]; then
        echo "  Sessions: $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(*) FROM sessions;" 2>/dev/null)"
        echo "  Projects: $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT COUNT(DISTINCT project_name) FROM sessions;" 2>/dev/null)"
        echo "  Last backup: $(sqlite3 "$BACKUP_PATH/backup_tracking.db" "SELECT MAX(timestamp) FROM backups;" 2>/dev/null)"
    fi
}

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Sync Copilot chat backups to a dedicated GitHub branch."
    echo ""
    echo "Options:"
    echo "  --init          Initialize the backup branch (run once)"
    echo "  --branch NAME   Use custom branch name (default: copilot-backup-data)"
    echo "  --status        Show sync status"
    echo "  --help, -h      Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --init       # Create the backup branch"
    echo "  $0              # Sync backups to GitHub"
    echo "  $0 --status     # Check sync status"
    echo ""
    echo "What gets synced:"
    echo "  • daily/*.md         - Daily activity summaries"
    echo "  • hourly/*.md        - Hourly incremental summaries"
    echo "  • ai-export/*.jsonl  - AI-friendly exports"
    echo "  • index/*.json       - Project indexes"
    echo ""
    echo "What stays local (not synced):"
    echo "  • raw/               - Original VS Code JSON files (large)"
    echo "  • markdown/          - Full markdown by project"
    echo "  • backup_tracking.db - SQLite database"
}

# Main
print_header

case "$COMMAND" in
    init)
        init_branch
        ;;
    sync)
        sync_backups
        ;;
    status)
        show_status
        ;;
    help)
        show_help
        ;;
esac
